Explanatory error message

diff --git a/roles/check_mk/server/templates/notifications/slack b/roles/check_mk/server/templates/notifications/slack
--- a/roles/check_mk/server/templates/notifications/slack
+++ b/roles/check_mk/server/templates/notifications/slack
@@ -26,5 +26,6 @@ case "$NOTIFY_WHAT" in
     send_with_optional_output "[$NOTIFY_NOTIFICATIONTYPE] [$NOTIFY_HOSTALIAS] $NOTIFY_SERVICEDESC is $NOTIFY_SERVICESTATE" "$NOTIFY_SERVICEOUTPUT"
     ;;
   *)
+    echo "Error: unrecognized subject for notification" >&2
     exit 1
 esac
